export type StudyConcept = {
  id: string;
  category: string;
  day: number;
  level: "필수" | "심화" | "보충";
  title: string;
  definition: string;
  steps: string[];
  trap: string;
  example: string;
  explanation: string;
  memoryRule: string;
  selfCheck: string;
  selfCheckAnswer: string;
  relatedQuestionIds: string[];
  pdfReferences: string[];
  officialUrl?: string;
};

const programmingPdf = "프로그래밍언어이론 PDF";
const theoryPdf = "이론 PDF";

export const studyConcepts: StudyConcept[] = [
  {
    id: "c-pointer", category: "C", day: 2, level: "필수", title: "주소와 값: p, &p, *p",
    definition: "포인터는 주소를 담는 변수다. &는 주소를 구하고, *는 저장된 주소를 따라가 값을 읽거나 바꾼다.",
    steps: ["일반 변수의 현재 값을 적는다.", "포인터가 어느 변수 또는 배열 원소를 가리키는지 화살표로 연결한다.", "*가 나오면 화살표를 따라가 실제 값을 읽는다."],
    trap: "선언문의 int *p와 식의 *p를 구분한다. p는 주소, *p는 그 주소에 있는 정수다. &p는 포인터 변수 자체의 주소다.",
    example: "int n = 12;\nint *p = &n;\n*p = 19;\nprintf(\"%d %d\", n, *p);",
    explanation: "p가 n을 가리킨다. *p = 19는 n을 19로 바꾼다. 출력은 19 19다.",
    memoryRule: "&는 주소를 얻고, *는 주소를 따라간다.", selfCheck: "p가 n을 가리킬 때 *p += 3을 실행하면 무엇이 바뀔까?", selfCheckAnswer: "포인터 주소가 아니라 n의 값이 3 증가한다.",
    relatedQuestionIds: ["2024-2-13", "2026-1-12"], pdfReferences: [programmingPdf, "포인터 5문제 PDF"],
  },
  {
    id: "c-array", category: "C", day: 2, level: "필수", title: "배열과 포인터 산술",
    definition: "대부분의 식에서 배열 이름은 첫 원소를 가리키는 포인터로 변환된다. p + 1은 다음 원소로 이동한다.",
    steps: ["배열 원소에 0부터 인덱스를 붙인다.", "p가 가리키는 인덱스를 표시한다.", "p + k를 k칸 이동으로 바꿔 읽은 뒤 역참조한다."],
    trap: "1바이트 이동이 아니라 가리키는 자료형 크기만큼 이동한다. sizeof(배열)과 sizeof(포인터)는 다르다.",
    example: "int a[] = {4, 9, 15, 22};\nint *p = a + 1;\nprintf(\"%d %d\", *p, *(p + 2));",
    explanation: "p는 a[1]을 가리킨다. *p는 9이고 p + 2는 a[3]이므로 9 22를 출력한다.",
    memoryRule: "a[i]는 *(a + i). 포인터 이동은 원소 단위.", selfCheck: "p = a일 때 p[2]와 *(p + 2)는 같은가?", selfCheckAnswer: "같다. 둘 다 a[2]의 값이다.",
    relatedQuestionIds: ["2026-1-01", "2024-2-13"], pdfReferences: [programmingPdf, "포인터 5문제 PDF"],
  },
  {
    id: "c-double-pointer", category: "C", day: 3, level: "필수", title: "이중 포인터를 두 번 따라가기",
    definition: "int **pp는 int * 변수의 주소를 담는다. *pp는 포인터이고 **pp는 그 포인터가 가리키는 정수다.",
    steps: ["pp → p → n처럼 주소 연결을 그린다.", "*pp 대입이면 p가 가리키는 대상을 바꾼다.", "**pp 대입이면 마지막 정수 값을 바꾼다."],
    trap: "*pp = &b와 **pp = b는 다르다. 앞은 연결 변경, 뒤는 값 변경이다.",
    example: "int a = 8, b = 17;\nint *p = &a;\nint **pp = &p;\n*pp = &b;\n**pp += 4;\nprintf(\"%d %d\", a, b);",
    explanation: "*pp = &b로 p가 b를 가리키게 된다. **pp += 4는 b를 21로 만든다. a는 그대로이므로 8 21이다.",
    memoryRule: "별 하나는 포인터까지, 별 둘은 실제 값까지.", selfCheck: "위 코드에서 마지막 *p의 값은?", selfCheckAnswer: "21. p가 이제 b를 가리킨다.",
    relatedQuestionIds: ["2024-3-16"], pdfReferences: [programmingPdf, "포인터 5문제 PDF"],
  },
  {
    id: "c-pointer-array", category: "C", day: 3, level: "심화", title: "포인터 배열과 배열 포인터",
    definition: "int *p[3]은 포인터 세 개의 배열이다. int (*p)[3]은 정수 세 개짜리 배열을 가리키는 포인터다.",
    steps: ["변수 이름 주변 괄호를 먼저 읽는다.", "포인터 배열이면 각 원소가 가리키는 행을 적는다.", "행 선택 후 열 선택 순서로 p[i][j]를 계산한다."],
    trap: "2차원 배열을 int **로 무조건 취급하면 안 된다. 배열 포인터의 +1은 행 하나를 이동한다.",
    example: "int a[2][3] = {{2, 4, 6}, {8, 10, 12}};\nint *rows[2] = {a[1], a[0]};\nprintf(\"%d %d\", rows[0][1], **rows);",
    explanation: "rows[0]은 두 번째 행이다. rows[0][1]은 10, **rows는 rows[0][0]인 8이므로 10 8이다.",
    memoryRule: "괄호 없는 *p[3]은 배열, 괄호 있는 (*p)[3]은 포인터.", selfCheck: "int (*p)[3]의 p + 1은 정수 몇 개만큼 이동할까?", selfCheckAnswer: "정수 3개, 즉 한 행만큼 이동한다.",
    relatedQuestionIds: ["2024-2-13"], pdfReferences: [programmingPdf, "포인터 5문제 PDF"],
  },
  {
    id: "c-struct", category: "C", day: 3, level: "필수", title: "구조체와 연결 리스트",
    definition: "구조체 변수의 멤버는 .으로, 구조체 포인터가 가리키는 멤버는 ->로 접근한다.",
    steps: ["각 노드를 이름과 값으로 그린다.", "next 같은 포인터 멤버를 화살표로 연결한다.", "->가 나올 때마다 해당 노드를 따라가 마지막 멤버 값을 읽는다."],
    trap: "노드의 값을 바꾸는 것과 next 연결을 바꾸는 것은 다르다. 순회 출력은 최종 연결을 기준으로 계산한다.",
    example: "struct Node { int value; struct Node *next; };\nstruct Node b = {30, 0};\nstruct Node a = {10, &b};\nstruct Node *head = &a;\nprintf(\"%d\", head->next->value);",
    explanation: "head → a → b로 이동한다. b.value가 30이므로 30을 출력한다.",
    memoryRule: "p->x는 (*p).x. 화살표 하나마다 노드를 따라간다.", selfCheck: "head->value와 head->next->value는 같은 노드를 읽을까?", selfCheckAnswer: "아니다. 앞은 현재 노드, 뒤는 다음 노드다.",
    relatedQuestionIds: ["2024-2-19", "2024-3-12"], pdfReferences: [programmingPdf, "구조체 3문제 PDF"],
  },
  {
    id: "c-call", category: "C", day: 2, level: "필수", title: "값 전달과 주소 전달",
    definition: "C의 인자는 값이 복사되어 전달된다. 포인터 값을 전달하면 복사된 주소로 원본을 수정할 수 있다.",
    steps: ["함수 매개변수에 복사된 값 또는 주소를 적는다.", "지역 변수 변경인지 *p를 통한 원본 변경인지 구분한다.", "함수에서 돌아온 뒤 호출자의 값만 다시 확인한다."],
    trap: "포인터도 값으로 전달된다. 함수 안에서 p 자체를 바꾸는 것과 *p를 바꾸는 것은 다르다.",
    example: "void byValue(int x) { x = 99; }\nvoid byAddress(int *p) { *p = 99; }\nint n = 7;\nbyValue(n);   // n은 7\nbyAddress(&n); // n은 99",
    explanation: "byValue는 복사본만 바꾼다. byAddress는 n의 주소를 받아 그곳의 값을 바꾼다.",
    memoryRule: "함수 안에서 원본이 바뀌는지 보려면 대입 대상에 *가 있는지 확인한다.", selfCheck: "함수 안에서 p = NULL이면 호출자의 포인터도 NULL이 될까?", selfCheckAnswer: "일반적인 int * 인자라면 아니다. 포인터 복사본만 바뀐다.",
    relatedQuestionIds: ["2024-2-18"], pdfReferences: [programmingPdf, "사용자정의함수 9문제 PDF"],
  },
  {
    id: "c-control", category: "C", day: 2, level: "필수", title: "제어문과 비트 연산 추적",
    definition: "반복문의 갱신 시점, switch의 break, 정수 나눗셈과 비트 연산을 한 줄씩 추적한다.",
    steps: ["변수 표를 만들고 반복 횟수마다 새 값을 적는다.", "switch는 일치 case부터 break를 만날 때까지 실행한다.", "비트 계산은 작은 값을 2진수로 쓰고 결과를 다시 10진수로 바꾼다."],
    trap: "switch는 break가 없으면 다음 case와 default까지 이어진다. 한 식에서 같은 변수를 여러 번 갱신하는 C 코드는 평가 순서 문제가 있을 수 있다.",
    example: "int n = 3;\nswitch (n) {\n  case 3: n += 2;\n  default: n += 4;\n}\nprintf(\"%d\", n);",
    explanation: "case 3에서 5가 되고 break가 없어 default에서 9가 된다.",
    memoryRule: "case는 시작점, break는 종료점.", selfCheck: "5 & 3, 5 | 3, 5 ^ 3의 결과는?", selfCheckAnswer: "1, 7, 6. 101과 011을 자리별로 계산한다.",
    relatedQuestionIds: ["2024-2-18", "2024-1-02"], pdfReferences: [programmingPdf, "제어문 14문제 PDF"],
  },
  {
    id: "c-recursion", category: "C", day: 3, level: "심화", title: "재귀와 트리 순회",
    definition: "재귀 함수는 종료 조건까지 호출을 쌓고, 돌아오면서 결과를 결합한다. 트리 순회 이름은 루트를 방문하는 위치로 구분한다.",
    steps: ["종료 조건과 반환값부터 확인한다.", "호출별 인자와 결과를 표로 적는다.", "전위는 루트-왼쪽-오른쪽, 중위는 왼쪽-루트-오른쪽, 후위는 왼쪽-오른쪽-루트로 방문한다."],
    trap: "함수가 호출된 순서와 printf나 카운터가 실행되는 순서를 혼동하지 않는다. 출력문이 재귀 호출 앞인지 뒤인지 표시한다.",
    example: "int f(int n) {\n  if (n <= 1) return 1;\n  return n * f(n - 1);\n}\n// f(4) = 4 * 3 * 2 * 1 = 24",
    explanation: "f(1)이 1을 반환한 뒤 f(2), f(3), f(4)의 결과가 차례로 정해진다.",
    memoryRule: "재귀는 내려갈 때 인자, 올라올 때 반환값.", selfCheck: "왼쪽, 오른쪽 재귀 호출 뒤에 출력하면 어떤 순회인가?", selfCheckAnswer: "후위 순회다. 자식들을 먼저 처리하고 루트를 출력한다.",
    relatedQuestionIds: [], pdfReferences: [programmingPdf, "사용자정의함수 9문제 PDF"],
  },
  {
    id: "c-function-pointer", category: "C", day: 3, level: "심화", title: "함수 포인터와 출력 서식",
    definition: "함수 포인터는 함수를 가리킨다. 호출 결과가 포인터라면 반환 주소를 계산한 뒤 역참조하고 출력 서식을 적용한다.",
    steps: ["반환형과 매개변수형을 먼저 읽는다.", "함수 호출 결과가 값인지 주소인지 적는다.", "%d, %x, %.2f 중 실제 서식에 맞게 최종 답을 쓴다."],
    trap: "32를 %x로 출력하면 20이다. 답안에 0x를 자동으로 붙이지 않는다. %.2f는 소수점 두 자리를 남긴다.",
    example: "int *next(int *p) { return p + 1; }\nint a[] = {18, 48};\nint *(*fn)(int *) = next;\nprintf(\"%x\", *fn(a));",
    explanation: "fn(a)는 a[1]의 주소다. 역참조하면 48, 16진수로 30을 출력한다.",
    memoryRule: "호출 → 반환 주소 → 역참조 → 출력 서식.", selfCheck: "정수 16을 %x로 출력하면?", selfCheckAnswer: "10. 16진수 두 자리이며 0x는 없다.",
    relatedQuestionIds: ["2026-1-12", "2026-1-01"], pdfReferences: [programmingPdf, "사용자정의함수 9문제 PDF"],
  },
  {
    id: "java-binding", category: "Java", day: 4, level: "필수", title: "오버라이딩과 필드 바인딩",
    definition: "인스턴스 메서드의 오버라이딩은 실제 객체에 따라 선택된다. 같은 이름의 필드는 참조 변수의 선언 타입으로 선택된다.",
    steps: ["참조 변수 타입과 new로 만든 실제 객체 타입을 따로 적는다.", "필드 접근은 선언 타입을 본다.", "재정의된 인스턴스 메서드는 실제 객체 타입을 본다."],
    trap: "static 메서드는 인스턴스 메서드처럼 오버라이딩되지 않는다. 필드 숨김을 메서드 재정의와 같은 규칙으로 계산하면 틀린다.",
    example: "class A { int x = 2; int f() { return 10; } }\nclass B extends A { int x = 7; int f() { return 20; } }\nA a = new B();\nSystem.out.print(a.x + a.f());",
    explanation: "a.x는 A의 2, a.f()는 B의 20이다. 합은 22다.",
    memoryRule: "필드는 선언 타입, 재정의된 인스턴스 메서드는 실제 객체.", selfCheck: "A a = new B()에서 a.f()는 어느 클래스 메서드인가?", selfCheckAnswer: "B가 f를 올바르게 오버라이딩했다면 B.f()다.",
    relatedQuestionIds: ["2024-3-11", "2024-1-16"], pdfReferences: [programmingPdf, "JAVA활용 9문제 PDF"], officialUrl: "https://docs.oracle.com/javase/tutorial/java/IandI/override.html",
  },
  {
    id: "java-overload", category: "Java", day: 4, level: "심화", title: "오버로딩을 먼저, 오버라이딩을 나중에",
    definition: "오버로딩은 컴파일 시 참조 타입과 인자 타입으로 메서드 시그니처를 정한다. 이후 오버라이딩이 적용된다.",
    steps: ["호출 위치에서 보이는 메서드 목록을 찾는다.", "인자의 컴파일 시 타입으로 오버로드를 선택한다.", "선택된 시그니처의 재정의가 있으면 실제 객체 구현을 실행한다."],
    trap: "실제 객체에 더 구체적인 오버로드가 있다고 컴파일러가 그 메서드를 다시 고르는 것은 아니다.",
    example: "void f(Object x) { ... }\nvoid f(String x) { ... }\nObject value = \"hello\";\nf(value);",
    explanation: "value의 선언 타입이 Object이므로 f(Object)를 선택한다. 문자열 객체라는 이유만으로 f(String)를 고르지 않는다.",
    memoryRule: "시그니처 선택은 컴파일 때, 재정의 선택은 실행 때.", selfCheck: "같은 메서드 이름에 매개변수 타입이 다르면 무엇인가?", selfCheckAnswer: "오버로딩이다.",
    relatedQuestionIds: ["2026-1-07", "2024-3-19"], pdfReferences: [programmingPdf, "JAVA활용 9문제 PDF"],
  },
  {
    id: "java-super", category: "Java", day: 4, level: "필수", title: "생성자, super와 접근 제어",
    definition: "자식 객체를 만들면 부모 생성자부터 초기화가 진행된다. super(...)는 부모 생성자, super.f()는 부모 메서드를 호출한다.",
    steps: ["생성자 호출을 부모 방향으로 추적한다.", "부모 초기화 뒤 자식 초기화로 내려온다.", "private, 기본, protected, public 접근 범위를 따로 확인한다."],
    trap: "private 멤버는 자식에서 직접 접근할 수 없다. 기본 접근은 같은 패키지다. protected의 다른 패키지 접근에는 상속 및 참조 제약이 있다.",
    example: "class A {\n  A(int n) { System.out.print(n); }\n}\nclass B extends A {\n  B() { super(4); System.out.print(8); }\n}\n// new B() 출력: 48",
    explanation: "부모 생성자의 4가 먼저, 자식 생성자의 8이 뒤에 출력된다.",
    memoryRule: "객체 초기화는 부모부터. private는 직접 접근 불가.", selfCheck: "접근 제한자를 쓰지 않은 멤버는 어디서 접근 가능한가?", selfCheckAnswer: "같은 패키지에서 접근 가능하다.",
    relatedQuestionIds: ["2024-1-10"], pdfReferences: [programmingPdf, "JAVA활용 9문제 PDF"],
  },
  {
    id: "java-output", category: "Java", day: 4, level: "필수", title: "문자열 결합과 참조 비교",
    definition: "+는 왼쪽부터 계산한다. 문자열을 만나면 문자열 결합이 된다. 배열의 ==는 내용이 아니라 같은 객체인지 비교한다.",
    steps: ["+를 왼쪽부터 괄호로 묶어 본다.", "문자열이 되는 첫 위치를 표시한다.", "배열 비교에서는 생성된 객체가 같은지 확인한다."],
    trap: "문자(char)는 문자열(String)과 다르다. 배열 내용이 같아도 각각 new로 만들었으면 ==는 false다.",
    example: "System.out.print(3 + 4 + \"5\" + 6);\n// 출력: 756\nint[] a = {1, 2};\nint[] b = {1, 2};\n// a == b: false",
    explanation: "3 + 4가 먼저 정수 7이 되고, 문자열 5와 6이 이어진다.",
    memoryRule: "문자열 전까지 덧셈, 문자열부터 이어 붙임.", selfCheck: "\"3\" + 4 + 5의 결과는?", selfCheckAnswer: "345다. 시작부터 문자열 결합이다.",
    relatedQuestionIds: ["2026-1-17", "2024-2-01"], pdfReferences: [programmingPdf, "JAVA활용 9문제 PDF"],
  },
  {
    id: "java-exception", category: "Java", day: 4, level: "필수", title: "예외 처리와 finally",
    definition: "발생한 예외를 처리할 첫 번째 맞는 catch가 실행된다. 정상 흐름과 예외 흐름 뒤에 finally를 추적한다.",
    steps: ["예외가 발생한 지점 이후 try의 남은 줄을 건너뛴다.", "일치하는 catch 하나만 실행한다.", "finally의 변수 변경까지 반영한다."],
    trap: "더 넓은 Exception catch를 앞에 놓으면 뒤의 하위 예외 catch가 도달 불가할 수 있다. 프로세스 강제 종료처럼 finally가 실행되지 않는 경우도 있다.",
    example: "int n = 0;\ntry { throw new NullPointerException(); }\ncatch (NullPointerException e) { n += 2; }\nfinally { n += 10; }\n// n: 12",
    explanation: "해당 catch에서 2가 되고 finally에서 10을 더한다.",
    memoryRule: "예외 지점 → catch 하나 → finally.", selfCheck: "예외가 없으면 finally를 건너뛰는가?", selfCheckAnswer: "일반적인 정상 종료에서는 finally도 실행한다.",
    relatedQuestionIds: ["2024-3-18"], pdfReferences: [programmingPdf, "JAVA활용 9문제 PDF"],
  },
  {
    id: "python-slice", category: "Python", day: 5, level: "필수", title: "슬라이싱과 음수 step",
    definition: "sequence[start:stop:step]은 시작을 포함하고 끝을 제외한다. step이 음수이면 역방향으로 이동한다.",
    steps: ["원소에 인덱스를 붙인다.", "step 부호로 진행 방향을 정한다.", "시작부터 step만큼 이동하되 stop은 포함하지 않는다."],
    trap: "[::-1]과 [:-1:-1]은 같지 않다. 음수 step에서 생략한 끝과 명시적 -1은 다르다.",
    example: "a = [2, 4, 6, 8, 10]\nprint(a[1:4:2])\nprint(a[::-2])",
    explanation: "첫 출력은 [4, 8], 두 번째는 [10, 6, 2]다.",
    memoryRule: "시작 포함, 끝 제외, 방향은 step.", selfCheck: "'ABCDE'[1:4]의 결과는?", selfCheckAnswer: "BCD다.",
    relatedQuestionIds: ["2026-1-13"], pdfReferences: [programmingPdf, "Python활용 6문제 PDF"], officialUrl: "https://docs.python.org/3/library/stdtypes.html#common-sequence-operations",
  },
  {
    id: "python-copy", category: "Python", day: 5, level: "심화", title: "얕은 복사와 내부 리스트 공유",
    definition: "얕은 복사는 바깥 컨테이너만 새로 만든다. 내부의 리스트 같은 객체는 여전히 공유될 수 있다.",
    steps: ["바깥 리스트와 안쪽 리스트를 별도 상자로 그린다.", "슬라이스 복사 후 어떤 내부 객체가 공유되는지 표시한다.", "내부 객체 수정과 바깥 슬롯 재대입을 구분한다."],
    trap: "리스트의 +=는 대개 기존 리스트를 확장한다. 새 리스트를 만들어 슬롯에 대입하는 +와 공유 영향이 다르다.",
    example: "a = [[1], [2]]\nb = a[:]\nb[0].append(9)\nprint(a)\n# [[1, 9], [2]]",
    explanation: "a[0]과 b[0]은 같은 내부 리스트를 가리키므로 append 결과가 둘 모두에서 보인다.",
    memoryRule: "겉은 복사돼도 속은 공유될 수 있다.", selfCheck: "b[0] = [7]처럼 슬롯을 바꾸면 a[0]도 바뀌는가?", selfCheckAnswer: "아니다. 새 객체를 b의 슬롯에 연결한다.",
    relatedQuestionIds: ["2026-1-14"], pdfReferences: [programmingPdf, "Python활용 6문제 PDF"], officialUrl: "https://docs.python.org/3/library/copy.html",
  },
  {
    id: "python-collections", category: "Python", day: 5, level: "필수", title: "딕셔너리, 집합과 출력 순서",
    definition: "dict는 키와 값을 연결하고 삽입 순서를 보존한다. set은 중복을 제거하지만 순서에 의존하면 안 된다.",
    steps: ["키 삽입, 기존 키 값 갱신, 키 삭제를 구분한다.", "items()는 키와 값 쌍으로 읽는다.", "set 결과는 원소 구성을 확인하고 표시 순서를 단정하지 않는다."],
    trap: "기존 dict 키의 값을 바꾸는 것은 키를 맨 뒤로 보내지 않는다. 집합 출력 순서를 단답 문자열처럼 고정하면 안 된다.",
    example: "d = {'a': 1, 'b': 2}\nd['a'] = 5\nd['c'] = 3\nprint(list(d))\n# ['a', 'b', 'c']",
    explanation: "a의 값만 바뀌고 위치는 유지된다. 새 키 c가 마지막에 추가된다.",
    memoryRule: "dict는 키 순서, set은 원소 구성.", selfCheck: "{1, 1, 2}의 원소 개수는?", selfCheckAnswer: "2개다. 중복 1은 하나만 남는다.",
    relatedQuestionIds: [], pdfReferences: [programmingPdf, "Python활용 6문제 PDF"], officialUrl: "https://docs.python.org/3/library/stdtypes.html#mapping-types-dict",
  },
  {
    id: "python-strings", category: "Python", day: 5, level: "필수", title: "split, join, range와 출력 형식",
    definition: "split은 문자열을 나누고 join은 문자열 원소들을 연결한다. range의 끝은 제외하며 print의 end가 출력 사이를 결정한다.",
    steps: ["문자열과 리스트 상태를 각 줄마다 적는다.", "range의 실제 원소를 먼저 펼친다.", "print의 구분자 sep와 끝 문자열 end를 확인한다."],
    trap: "split()은 연속 공백을 묶어 처리한다. split(' ')은 공백 하나하나를 구분자로 사용해 빈 문자열이 생길 수 있다.",
    example: "s = 'a  b'\nprint(s.split())\nprint(s.split(' '))\nprint('-'.join(['x', 'y']))",
    explanation: "['a', 'b'], ['a', '', 'b'], x-y가 각각 출력된다.",
    memoryRule: "나눌 때 split, 합칠 때 join. 빈칸은 실제 출력대로.", selfCheck: "range(1, 6, 2)의 값은?", selfCheckAnswer: "1, 3, 5다.",
    relatedQuestionIds: ["2026-1-08", "2026-1-13"], pdfReferences: [programmingPdf, "Python활용 6문제 PDF"], officialUrl: "https://docs.python.org/3/library/stdtypes.html#str.split",
  },
  {
    id: "sql-join", category: "SQL", day: 6, level: "필수", title: "조인 결과를 직접 표로 만들기",
    definition: "INNER JOIN은 조건이 일치하는 행 조합만 남긴다. OUTER JOIN은 기준 테이블의 미일치 행도 NULL을 채워 남긴다.",
    steps: ["기준 테이블과 조인 조건을 표시한다.", "각 기준 행마다 일치하는 상대 행을 모두 적는다.", "미일치 행을 유지하는지 확인하고 WHERE를 적용한다."],
    trap: "일치 행이 여러 개면 결과가 늘어난다. LEFT JOIN 뒤 WHERE 오른쪽열 = 값 조건은 NULL 행을 제거할 수 있다.",
    example: "A: (id=1), (id=2)\nB: (aid=1, v='x'), (aid=1, v='y')\nA LEFT JOIN B ON A.id = B.aid\n결과: (1,'x'), (1,'y'), (2,NULL)",
    explanation: "id=1은 두 번 일치하므로 두 행이다. id=2는 미일치지만 왼쪽 기준이라 남는다.",
    memoryRule: "조인은 행 짝짓기. 외부 조인은 기준 쪽 미일치도 유지.", selfCheck: "위 결과의 COUNT(*)는?", selfCheckAnswer: "3이다. COUNT(B.v)는 NULL을 빼서 2다.",
    relatedQuestionIds: ["2026-1-18", "2024-1-08"], pdfReferences: [theoryPdf, "SQL 17문제 PDF"],
  },
  {
    id: "sql-null", category: "SQL", day: 6, level: "필수", title: "NULL과 집계 함수",
    definition: "NULL은 값이 없거나 알려지지 않았음을 뜻한다. COUNT(*)는 행 수, COUNT(열)은 NULL이 아닌 값 수를 센다.",
    steps: ["WHERE를 먼저 적용한다.", "COUNT(*)인지 COUNT(열)인지 확인한다.", "DISTINCT가 있으면 중복 제거 뒤 개수를 센다."],
    trap: "NULL = NULL은 참이 아니다. NULL 검사는 IS NULL을 쓴다. NOT IN의 목록에 NULL이 있으면 예상과 다른 결과가 나올 수 있다.",
    example: "값: 10, NULL, 10, 20\nCOUNT(*) = 4\nCOUNT(값) = 3\nCOUNT(DISTINCT 값) = 2\nAVG(값) = 40 / 3",
    explanation: "AVG도 NULL을 제외한다. 평균 분모가 전체 행 수 4가 아니라 비NULL 값 수 3이다.",
    memoryRule: "별은 행, 열은 비NULL, DISTINCT는 중복 제거.", selfCheck: "NULL을 찾는 조건은 x = NULL인가?", selfCheckAnswer: "x IS NULL이다.",
    relatedQuestionIds: ["2026-1-09"], pdfReferences: [theoryPdf, "SQL 17문제 PDF"],
  },
  {
    id: "sql-order", category: "SQL", day: 6, level: "필수", title: "WHERE, GROUP BY, HAVING과 정렬",
    definition: "WHERE는 개별 행을, HAVING은 집계한 그룹을 거른다. ORDER BY에서 ASC는 오름차순, DESC는 내림차순이다.",
    steps: ["FROM과 JOIN으로 대상 행을 만든다.", "WHERE로 행을 거른 뒤 GROUP BY로 묶는다.", "HAVING으로 그룹을 거르고 출력 열과 정렬을 계산한다."],
    trap: "이 순서는 결과 이해를 위한 논리 흐름이며 DB의 실제 물리 실행 순서를 뜻하지 않는다. AND는 OR보다 먼저 묶인다.",
    example: "SELECT dept, COUNT(*)\nFROM employee\nWHERE salary >= 200\nGROUP BY dept\nHAVING COUNT(*) >= 2\nORDER BY dept DESC;",
    explanation: "급여 조건을 만족한 직원만 부서별로 센다. 2명 이상인 부서를 남기고 부서명을 내림차순 정렬한다.",
    memoryRule: "WHERE는 행, HAVING은 그룹.", selfCheck: "성이 김인 이름을 LIKE로 찾는 패턴은?", selfCheckAnswer: "'김%'다. %는 0개 이상의 문자, _는 문자 하나다.",
    relatedQuestionIds: ["2024-1-18"], pdfReferences: [theoryPdf, "SQL 17문제 PDF"], officialUrl: "https://www.postgresql.org/docs/current/tutorial-agg.html",
  },
  {
    id: "sql-subquery", category: "SQL", day: 6, level: "심화", title: "서브쿼리와 상관 서브쿼리",
    definition: "서브쿼리는 다른 SQL 안의 조회다. 상관 서브쿼리는 바깥 행의 값을 내부에서 참조한다.",
    steps: ["외부 참조가 없는 내부 조회 결과부터 계산한다.", "상관 조회라면 외부 행 하나를 고정하고 내부 조건을 계산한다.", "IN, EXISTS, 비교 연산에 맞춰 외부 행을 남긴다."],
    trap: "서브쿼리를 항상 단 한 번만 실행한다고 생각하지 않는다. EXISTS는 반환한 값 자체보다 행이 있는지 본다.",
    example: "SELECT name FROM employee e\nWHERE salary > (\n  SELECT AVG(salary) FROM employee\n  WHERE dept = e.dept\n);",
    explanation: "자신이 속한 부서의 평균 급여보다 높은 직원만 남는다. 전체 회사 평균과 비교하는 쿼리가 아니다.",
    memoryRule: "내부에 외부 별칭이 보이면 행마다 조건을 다시 본다.", selfCheck: "EXISTS는 서브쿼리의 반환 행이 하나라도 있으면 참인가?", selfCheckAnswer: "그렇다. 반환 열의 값이 NULL이어도 행의 존재가 핵심이다.",
    relatedQuestionIds: ["2026-1-18", "2024-1-13"], pdfReferences: [theoryPdf, "SQL 17문제 PDF"],
  },
  {
    id: "db-normalization", category: "DB·설계", day: 9, level: "필수", title: "키, 함수 종속과 정규화",
    definition: "정규화는 함수 종속을 바탕으로 중복과 갱신 이상을 줄이는 설계 과정이다. 후보키는 유일성과 최소성을 만족한다.",
    steps: ["후보키를 표시하고 X → Y 종속을 적는다.", "1NF의 원자값, 2NF의 부분 종속 제거를 확인한다.", "3NF의 이행 종속 제거, BCNF의 모든 결정자 후보키 조건을 확인한다."],
    trap: "부분 종속 제거만으로 3NF라고 단정하면 안 된다. 표의 현재 값만 보고 모든 함수 종속을 확정하지 말고 제시한 업무 규칙을 본다.",
    example: "(학생, 과목) → 점수\n학생 → 학생명\n복합키의 일부인 학생만으로 학생명이 정해짐\n→ 학생 정보와 수강 정보를 분리해 부분 종속 제거",
    explanation: "복합키의 일부에 의존하는 비키 속성이 있으면 2NF를 위반한다.",
    memoryRule: "1 원자, 2 부분 제거, 3 이행 제거, BCNF 결정자 확인.", selfCheck: "슈퍼키에서 불필요한 속성을 모두 제거한 키는?", selfCheckAnswer: "후보키다.",
    relatedQuestionIds: ["2024-1-06", "2024-3-15", "2024-2-02"], pdfReferences: [theoryPdf, "키워드찾기 130문제 PDF"],
  },
  {
    id: "db-transaction", category: "DB·설계", day: 9, level: "필수", title: "트랜잭션과 무결성",
    definition: "트랜잭션은 함께 성공하거나 함께 취소되어야 하는 작업 단위다. ACID는 원자성, 일관성, 격리성, 지속성이다.",
    steps: ["문제의 행동을 성공/취소, 규칙 유지, 동시 실행, 장애 후 보존으로 나눈다.", "각 행동을 ACID와 연결한다.", "PK, FK, CHECK, NOT NULL 제약조건의 대상을 확인한다."],
    trap: "일관성과 격리성을 혼동하지 않는다. CHECK는 값의 조건이고 FK는 다른 테이블의 참조 관계를 검사한다.",
    example: "계좌 A에서 10 차감 + 계좌 B에 10 추가\n둘 중 하나만 반영되면 안 됨 → 원자성\n완료된 이체가 장애 뒤에도 남음 → 지속성",
    explanation: "원자성은 전부 성공 또는 전부 취소, 지속성은 커밋 결과의 보존이다.",
    memoryRule: "A 전부, C 규칙, I 간섭, D 보존.", selfCheck: "참조 테이블의 키를 가리키는 제약조건은?", selfCheckAnswer: "외래키 FOREIGN KEY다.",
    relatedQuestionIds: ["2026-1-10"], pdfReferences: [theoryPdf, "SQL 17문제 PDF"],
  },
  {
    id: "network-subnet", category: "네트워크", day: 7, level: "필수", title: "서브넷: 블록 크기로 계산하기",
    definition: "IPv4의 /n은 네트워크 비트 수다. 호스트 비트는 32 - n이고 일반적인 서브넷의 주소 개수는 2의 호스트비트 수 제곱이다.",
    steps: ["프리픽스에서 호스트 비트 수를 구한다.", "경계 옥텟의 블록 크기를 계산한다.", "IP가 속한 구간의 처음은 네트워크, 끝은 브로드캐스트로 적는다."],
    trap: "보통 사용 가능 호스트 수는 전체에서 2를 뺀다. /31의 지점 간 링크와 /32는 예외이므로 문제 조건을 본다.",
    example: "192.168.4.70/26\n블록: 64개\n구간: 64~127\n네트워크: 192.168.4.64\n브로드캐스트: 192.168.4.127\n일반 호스트 수: 62",
    explanation: "70이 64~127 구간에 들어간다. 사용 가능 주소는 .65부터 .126까지다.",
    memoryRule: "구간 첫 주소는 망, 마지막은 방송, 그 사이는 호스트.", selfCheck: "/27을 같은 크기의 두 서브넷으로 나누면 프리픽스는?", selfCheckAnswer: "/28이다. 네트워크 비트를 하나 추가한다.",
    relatedQuestionIds: ["2026-1-11", "2024-1-05"], pdfReferences: [theoryPdf],
  },
  {
    id: "network-layers", category: "네트워크", day: 7, level: "필수", title: "OSI 계층과 TCP·UDP",
    definition: "OSI는 물리, 데이터링크, 네트워크, 전송, 세션, 표현, 응용의 7계층 모델이다. IP는 네트워크, TCP·UDP는 전송 계층이다.",
    steps: ["문제의 대상이 비트, 프레임, 패킷, 세그먼트인지 확인한다.", "MAC, IP, 포트 번호 중 어떤 주소를 쓰는지 구분한다.", "전송 방식이 TCP의 연결·재전송인지 UDP의 비연결인지 확인한다."],
    trap: "TCP는 스트림의 신뢰성·순서를 제공한다. UDP가 무조건 더 빠르거나 오류 검사를 하지 않는다고 단정하면 안 된다.",
    example: "스위치: 주로 MAC과 프레임\n라우터: IP와 패킷\nTCP/UDP 포트: 응용 프로세스 구분\nHTTPS: HTTP를 TLS로 보호",
    explanation: "주소의 용도부터 정하면 계층과 장비를 함께 구분하기 쉽다.",
    memoryRule: "MAC은 링크, IP는 망, 포트는 프로세스.", selfCheck: "IPsec은 주로 어느 계층을 보호하는가?", selfCheckAnswer: "네트워크 계층의 IP 통신이다.",
    relatedQuestionIds: ["2024-2-05", "2024-2-08"], pdfReferences: [theoryPdf, "키워드찾기 130문제 PDF"],
  },
  {
    id: "network-routing", category: "네트워크", day: 7, level: "필수", title: "RIP, OSPF와 HDLC",
    definition: "RIP는 홉 수 기반 거리 벡터 프로토콜이다. OSPF는 링크 상태 정보를 사용한다. HDLC는 데이터링크 제어 프로토콜이다.",
    steps: ["경로 선택 기준이 홉 수인지 비용인지 확인한다.", "문제의 간선 정보로 각 경로 비용을 합한다.", "HDLC는 데이터 전달, 감독, 비번호 제어 프레임을 구분한다."],
    trap: "RIP의 홉 수와 임의의 링크 비용을 혼용하지 않는다. OSPF의 링크 상태 설명과 RIP의 거리 벡터 설명을 바꿔 외우지 않는다.",
    example: "RIP: 거리 벡터, 홉 수, 최대 유효 홉 15\nOSPF: 링크 상태, 다익스트라\nHDLC: I 정보 / S 감독 / U 비번호",
    explanation: "I는 사용자 데이터, S는 흐름·오류 제어, U는 링크 관리 등의 제어에 사용된다.",
    memoryRule: "RIP는 홉, OSPF는 링크 상태. HDLC는 I·S·U.", selfCheck: "다익스트라로 최단 경로를 계산하는 대표 IGP는?", selfCheckAnswer: "OSPF다.",
    relatedQuestionIds: ["2024-1-07", "2024-2-11", "2026-1-06"], pdfReferences: [theoryPdf],
  },
  {
    id: "os-scheduling", category: "운영체제", day: 8, level: "필수", title: "스케줄링과 평균 대기시간",
    definition: "CPU 스케줄링은 준비 상태 프로세스의 실행 순서를 정한다. SRT는 남은 실행시간이 더 짧은 작업이 도착하면 선점한다.",
    steps: ["도착 시간과 실행 시간을 표에 적는다.", "도착·완료·타임퀀텀 경계마다 다음 작업을 선택해 간트 차트를 그린다.", "대기시간 = 완료시간 - 도착시간 - 실행시간으로 각 작업을 계산한다."],
    trap: "SJF는 비선점, SRT는 선점이다. 응답시간, 반환시간, 대기시간은 다른 값이다. 동률 처리 기준은 문제 조건을 따른다.",
    example: "A: 도착 0, 실행 5 / B: 도착 1, 실행 2\nSRT: A(0~1) → B(1~3) → A(3~7)\n대기 A=7-0-5=2, B=3-1-2=0\n평균 대기=1",
    explanation: "B 도착 시 A의 남은 4보다 B의 2가 짧아 선점한다.",
    memoryRule: "대기는 완료 - 도착 - 실행.", selfCheck: "RR에서 작업을 번갈아 나누는 기준 시간은?", selfCheckAnswer: "타임퀀텀이다.",
    relatedQuestionIds: ["2024-2-12"], pdfReferences: [theoryPdf],
  },
  {
    id: "os-page", category: "운영체제", day: 8, level: "필수", title: "페이지 교체와 페이지 부재",
    definition: "참조한 페이지가 메모리에 없으면 페이지 부재가 발생한다. 빈 프레임이 없을 때 교체 알고리즘으로 대상을 정한다.",
    steps: ["참조열을 한 칸씩 읽는다.", "적중인지 부재인지 표시한다.", "FIFO는 들어온 순서, LRU는 최근 사용 시각, LFU는 사용 횟수를 갱신한다."],
    trap: "초기 빈 프레임에 넣는 것도 부재다. LRU는 적중 때도 최근 사용을 갱신한다. LFU의 동률 규칙을 확인한다.",
    example: "프레임 2개 / 참조: 1, 2, 1, 3\nLRU: [1] → [1,2] → [1,2] → [1,3]\n부재: 처음 1, 처음 2, 마지막 3 → 총 3회",
    explanation: "마지막 3을 넣을 때 최근에 사용한 1을 남기고 2를 교체한다.",
    memoryRule: "FIFO는 들어온 때, LRU는 쓴 때, LFU는 쓴 횟수.", selfCheck: "페이지 적중도 부재 횟수를 늘리는가?", selfCheckAnswer: "아니다. 필요한 페이지가 메모리에 있으면 적중이다.",
    relatedQuestionIds: ["2024-1-09"], pdfReferences: [theoryPdf],
  },
  {
    id: "os-deadlock", category: "운영체제", day: 8, level: "필수", title: "교착 상태와 메모리 관리",
    definition: "교착 상태는 자원을 점유한 작업들이 서로의 자원을 기다려 진행하지 못하는 상태다.",
    steps: ["상호 배제, 점유 대기, 비선점, 순환 대기 조건을 찾는다.", "조건 제거는 예방, 안전 상태 검사는 회피로 구분한다.", "메모리 문제는 고정 크기 페이지와 가변 크기 세그먼트를 구분한다."],
    trap: "은행원 알고리즘은 회피다. 페이징은 내부 단편화, 세그먼테이션은 외부 단편화가 대표적으로 연결된다.",
    example: "A는 프린터를 잡고 스캐너를 기다림\nB는 스캐너를 잡고 프린터를 기다림\n→ 서로 기다리는 순환 관계",
    explanation: "두 자원을 항상 같은 순서로 얻도록 제한하면 순환 대기 조건을 깨는 예방 방법이 된다.",
    memoryRule: "상호·점유·비선점·순환. 예방은 조건 제거, 회피는 안전 확인.", selfCheck: "페이지 크기가 고정돼 마지막 페이지에 남는 공간은?", selfCheckAnswer: "내부 단편화다.",
    relatedQuestionIds: [], pdfReferences: [theoryPdf, "키워드찾기 130문제 PDF"],
  },
  {
    id: "security-basics", category: "보안", day: 8, level: "필수", title: "CIA, AAA와 보안 장비",
    definition: "CIA는 기밀성, 무결성, 가용성이다. AAA는 인증, 권한 부여, 사용 기록 관리다.",
    steps: ["누가 읽는지, 누가 바꾸는지, 언제 이용 가능한지를 나눈다.", "신원 확인과 권한 확인을 구분한다.", "탐지 중심 IDS와 차단 기능 IPS, 웹 공격 방어 WAF를 연결한다."],
    trap: "인증에 성공했다고 모든 데이터 접근 권한이 생기는 것은 아니다. 보안 장비의 이름만으로 모든 공격을 막는다고 단정하지 않는다.",
    example: "로그인으로 신원 확인 → Authentication\n관리자만 삭제 가능 → Authorization\n누가 언제 접근했는지 기록 → Accounting",
    explanation: "사용자를 확인하고, 허용 행동을 결정하고, 실제 사용을 기록하는 순서다.",
    memoryRule: "CIA 읽기·변경·이용, AAA 신원·권한·기록.", selfCheck: "서비스를 마비시키는 DDoS는 CIA 중 무엇을 주로 공격하는가?", selfCheckAnswer: "가용성이다.",
    relatedQuestionIds: ["2026-1-05"], pdfReferences: [theoryPdf, "키워드찾기 130문제 PDF"],
  },
  {
    id: "security-attacks", category: "보안", day: 8, level: "필수", title: "공격 용어를 행동으로 구분하기",
    definition: "공격 이름보다 표적, 유입 경로, 실행 행동을 확인하면 비슷한 용어를 구분하기 쉽다.",
    steps: ["특정 표적을 노리는지 불특정 다수인지 본다.", "메일, 문자, 웹, DNS, 공급망 중 경로를 표시한다.", "은닉, 암호화, 도청, 위장 중 행동을 붙인다."],
    trap: "스피어 피싱은 특정 표적을 겨냥한다. PDF의 불특정 다수 설명과 혼동하지 않는다. Rootkit은 은닉, 랜섬웨어는 금전 요구가 핵심이다.",
    example: "자주 가는 사이트 감염 → Watering Hole\n표적에게 맞춤 메일 → Spear Phishing\n침투 후 장기간 정보 수집 → APT\n시스템 내 존재 숨김 → Rootkit",
    explanation: "공격의 출발점과 목적을 한 쌍으로 묶어 기억한다.",
    memoryRule: "워터링홀은 방문지, 스피어는 표적 메일, 루트킷은 은닉.", selfCheck: "수집한 계정·비밀번호를 다른 서비스에도 대입하는 공격은?", selfCheckAnswer: "크리덴셜 스터핑이다.",
    relatedQuestionIds: ["2026-1-16", "2024-1-15", "2024-1-17"], pdfReferences: [theoryPdf, "키워드찾기 130문제 PDF"],
  },
  {
    id: "security-web", category: "보안", day: 8, level: "필수", title: "SQL Injection, XSS, CSRF와 TOCTOU",
    definition: "주입 공격은 데이터가 명령처럼 해석되는 문제를 이용한다. CSRF는 로그인한 사용자의 권한으로 원치 않는 요청을 보내게 한다.",
    steps: ["SQL 명령이 바뀌면 SQL Injection으로 본다.", "브라우저에서 악성 스크립트가 실행되면 XSS를 확인한다.", "확인과 사용 사이에 대상이 바뀌면 TOCTOU를 의심한다."],
    trap: "XSS와 CSRF는 같지 않다. 심볼릭 링크 자체가 악성인 것도 아니다. 공격 문맥에서 경로를 바꿔치기하는지 확인한다.",
    example: "SQL 문자열 연결 대신 매개변수 바인딩\n출력 문맥에 맞는 인코딩으로 XSS 방어\nCSRF 토큰과 적절한 쿠키 정책\n확인한 파일과 사용한 파일이 같은지 보장",
    explanation: "공격 이름과 대표 방어를 함께 기억하면 지문 속 행동을 구분하기 쉽다.",
    memoryRule: "SQL은 DB 명령, XSS는 브라우저 스크립트, CSRF는 위조 요청.", selfCheck: "파일 존재 확인 뒤 실제 사용 전에 경로가 바뀌는 위험은?", selfCheckAnswer: "TOCTOU 경쟁 조건이다.",
    relatedQuestionIds: ["2026-1-15"], pdfReferences: [theoryPdf],
  },
  {
    id: "security-crypto", category: "보안", day: 8, level: "필수", title: "암호화, 해시와 전자서명",
    definition: "대칭키는 같은 비밀키로 암복호화한다. 공개키 방식은 키 쌍을 사용한다. 암호학적 해시는 입력을 고정 길이 값으로 변환한다.",
    steps: ["원문 복원이 필요한지부터 확인한다.", "기밀 통신과 서명 검증의 키 사용 방향을 구분한다.", "AES의 블록·키 크기와 해시의 단방향·충돌 저항 특성을 정리한다."],
    trap: "해시는 복호화하지 않는다. 전자서명은 서명자의 개인키로 생성하고 공개키로 검증한다. AES 블록은 128비트, 키는 128/192/256비트다.",
    example: "기밀 통신: 수신자 공개키로 암호화 → 수신자 개인키로 복호화\n전자서명: 서명자 개인키로 서명 → 서명자 공개키로 검증\n해시: 변경 여부 확인 등에 사용",
    explanation: "키 방향을 목적과 연결한다. 해시값만으로 메시지 작성자 인증까지 자동 보장되지는 않는다.",
    memoryRule: "잠글 때 받는 사람 공개키, 서명할 때 내 개인키.", selfCheck: "AES의 키 길이가 256비트이면 블록도 256비트인가?", selfCheckAnswer: "아니다. AES 블록은 항상 128비트다.",
    relatedQuestionIds: ["2024-2-07"], pdfReferences: [theoryPdf, "키워드찾기 130문제 PDF"],
  },
  {
    id: "testing", category: "DB·설계", day: 9, level: "필수", title: "블랙박스, 커버리지와 통합 테스트",
    definition: "블랙박스는 명세의 입력과 결과, 화이트박스는 내부 구조를 기준으로 테스트를 설계한다.",
    steps: ["입력 구간 대표값은 동치 분할, 경계 전후 값은 경계값 분석으로 구분한다.", "문장, 분기, 개별 조건의 참·거짓 커버리지를 분리한다.", "하향식 통합에는 스텁, 상향식에는 드라이버를 연결한다."],
    trap: "조건 커버리지가 분기 커버리지를 항상 보장하지는 않는다. MC/DC는 조건 하나의 독립적인 결정 영향까지 확인한다.",
    example: "나이 20~29를 한 유효 구간으로 선택 → 동치 분할\n19, 20, 29, 30을 확인 → 경계값 분석\n하위 모듈을 대신하는 단순 반환 코드 → 스텁",
    explanation: "구간을 대표하는 값인지, 경계에 붙은 값인지부터 구분한다.",
    memoryRule: "대표값은 동치, 경계는 경계값. 아래 대역 스텁, 위 대역 드라이버.", selfCheck: "모든 분기 결과가 한 번씩 실행되는 커버리지는?", selfCheckAnswer: "분기 또는 결정 커버리지다.",
    relatedQuestionIds: ["2026-1-19", "2024-3-13", "2024-1-14"], pdfReferences: [theoryPdf, "키워드찾기 130문제 PDF"],
  },
  {
    id: "coupling-cohesion", category: "DB·설계", day: 9, level: "필수", title: "결합도와 응집도",
    definition: "결합도는 모듈 사이의 의존 정도, 응집도는 모듈 내부 요소가 한 목적에 모인 정도다.",
    steps: ["모듈 사이 문제인지 내부 요소 문제인지 먼저 나눈다.", "내용 직접 참조, 공통 전역, 제어 전달, 구조체 전달, 자료 전달을 구분한다.", "동일 자료, 실행 순서, 출력-입력 연결, 단일 목적을 응집도와 연결한다."],
    trap: "절차적은 순서가 핵심, 순차적은 앞 출력이 뒤 입력으로 연결된다. 교환적(통신적)은 같은 입출력 자료를 공유한다.",
    example: "낮은 결합도: 자료 → 스탬프 → 제어 → 외부 → 공통 → 내용\n높은 응집도: 우연 → 논리 → 시간 → 절차 → 교환 → 순차 → 기능",
    explanation: "내용 결합도는 가장 강한 의존, 기능적 응집도는 하나의 목적에 가장 잘 모인 상태다.",
    memoryRule: "결합은 낮게, 응집은 높게. 순차는 출력이 다음 입력.", selfCheck: "한 모듈이 다른 모듈 내부 변수에 직접 접근하면?", selfCheckAnswer: "내용 결합도다.",
    relatedQuestionIds: ["2026-1-20", "2024-2-16", "2024-2-09"], pdfReferences: [theoryPdf, "키워드찾기 130문제 PDF"],
  },
  {
    id: "patterns-uml", category: "DB·설계", day: 9, level: "필수", title: "디자인 패턴과 UML 관계",
    definition: "패턴은 반복되는 설계 문제의 해결 구조다. UML은 구조나 행동, 객체 관계를 시각적으로 나타낸다.",
    steps: ["생성·구조·행위 중 목적을 찾는다.", "관련 제품군 생성, 상태 통지, 구현 분리, 순회라는 행동을 패턴에 연결한다.", "상속, 부분-전체, 일시 사용, 일반 참조를 UML 관계와 구분한다."],
    trap: "Abstract Factory는 제품군 생성, Factory Method는 생성 메서드 재정의가 핵심이다. 집약과 합성은 생명주기 의존을 구분한다.",
    example: "제품군 교체: Abstract Factory\n상태 변경 통지: Observer\n추상과 구현 분리: Bridge\n내부를 숨긴 순회: Iterator\n상속: 일반화 / 일시 사용: 의존",
    explanation: "이름을 먼저 외우기보다 문제에서 하고 싶은 동작을 고른다.",
    memoryRule: "군 생성 AF, 통지 Observer, 구현 분리 Bridge, 순회 Iterator.", selfCheck: "객체의 상태 변경을 구독 객체에 알리는 패턴은?", selfCheckAnswer: "Observer다.",
    relatedQuestionIds: ["2026-1-02", "2024-1-20", "2024-2-10", "2024-3-14"], pdfReferences: [theoryPdf, "키워드찾기 130문제 PDF"],
  },
];
